[metadata]
name = mnix
version = 0.1.1
description = Stateless client/server remote development environments powered by Nix and Podman.
long_description = file: README.md
long_description_content_type = text/markdown
author = Avikant Srivastava
author_email = me@avikant.com
license = MIT

[options]
package_dir =
    = src
packages = find:

[options.packages.find]
where = src

[options.entry_points]
console_scripts =
    mnix = mnix.client.cli:main
    mnix-server = mnix.server.interfaces.cli:main
